---
machine:
  network:
    hostname: quark
  disks:
  - device: /dev/sdb
    partitions:
    - mountpoint: /var/mnt/longhorn-storage
  kubelet:
    extraMounts:
    - source: /var/mnt/longhorn-storage
      destination: /var/mnt/longhorn-storage
      type: bind
      options:
      - bind
      - rshared
      - rw
