apiVersion: v1
kind: Secret
metadata:
    name: photoprism-credentials
    namespace: photoprism
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:v2Babo6lcSiTKmURJkM=,iv:3eLgr1jbUgnwOaRVoiNs87njfXRfjRiXtg9cxpVX0rA=,tag:vlZgro3cGeAEJ05Ln4ewhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbDUxVGk2NUtyekFzQU5Z
            dGpwZHoySTc1dzJwM1FYZS9wVjVlaURTTlZVCnd0NnY3SU1TVjIrSkg1eFpFOGNR
            TkVEaVpmbUdHQnl5eXBlVDZwWUJwR2cKLS0tIDRyUVNMS0pSemdobmg4T2NPaURB
            NkhHZUdGd1I2YWpFaDNhSUk4Q29xUTQKQGZhROHxVhSXgDRzipp+/8IDXtRvrhHt
            I2Kqg1Qptl90ZvNaBOI9kOvf3ChFXr6F1830R/5VmKFR7tmpyHcd2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T04:19:50Z"
    mac: ENC[AES256_GCM,data:SXE4dnzYjj9SX4wASGSHoB+Id2gOLNGED6xn36lI9Ys8WZQPAhf1W0Qv4vUWC1sTAuGcHFTcufIBffZIDVHzeehDtBuDYyFxOmhdUbA8r3zN43u160z0yaHioCbWcVn3Of5b4vCBCz5RPdfCa+dohCVWyTmDyEL8Gx2gf9R0Ij0=,iv:bwwuSQca34lNaQSVv1qeJLfEmDwGnQmInb/Hlulzb7Y=,tag:1NIXVPaHASYSI8dSITXyKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
