---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
  - start: "192.168.0.20"
    stop: "192.168.0.99"
  serviceSelector:
    matchLabels:
      color: blue
