---
extends: default
rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
    level: error
  document-start:
    present: true
    level: error
  truthy:
    check-keys: false
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  empty-lines:
    max: 1
    level: warning
  key-duplicates: enable
  new-line-at-end-of-file:
    level: warning

# Ignore encrypted secret files - SOPS encryption doesn't preserve YAML formatting
# (indentation and document start markers "---"), so we exclude these files from linting
ignore: |
  infrastructure/*/secrets/*.yaml
