---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared
  - nginx
  - netbootxyz
  # IoT
  - mosquitto
  - mqtt-explorer
  # - n8n
  # - photoprism
  - pocketid
  - oauth2-proxy
