---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared
  - nginx
  - netbootxyz
  - mosquitto
  # - n8n
  # - photoprism
  - pocketid
  - whoami
  - oauth2-proxy
