apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:dvPuv8xq4kpOizW6vKTaKJBr4nHLlIT1nNjuVc5aB+++lMs9o2B4LQ==,iv:2Rn1e+EYZ6nGHLNLT/pndmafzZn0T+qE6Qnj5SBvH50=,tag:Akf+Gnp6UfFkp4/MfvrY6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUlkyN1VjcndFQS84bHZJ
            QTAyUFRHK29nVVdURUYzYXliZzJxWU1keUR3CjBsd1RtVGprMktkMlI3MCtoT2g2
            Mis0VXZydTdYUUhQcGFmUXBWWHNlM2sKLS0tIHdGakQ4cEpkZ2hRM1E4RFYyZkRz
            T0xVRmc0WEQyR1pldXBmSEJLa0lpUUEKhvjOljIDITIStSJehBhrWBMFgQMS3WWm
            4V4oCkO7vp8ON1anvbnzpsipIptxe3USDhcZ4/Ha/r1ARrkug0i2UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T02:07:02Z"
    mac: ENC[AES256_GCM,data:6F2JYJ746808R0RY5VqVOKf87NAlei92FFAD6NBr3b6cnT8Apn6ousu4GstR0DtGkChcz4TsAxsJ3LQ6oHWlty9ESaS2TExW3bejBNwSLrT20TVSAaaXO/wcR1OAl6w9fhzYssY3+wG2oLwrWrtGxkuzYm+qqVXdVIRaGtsXFaA=,iv:9RP13GuZu6gp+BGJ8NWMb2FVRWMOPg5Ybinf1hl1qvA=,tag:x2fOm7le8vNE1Op84ApEtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
