apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: external-dns
data:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:GERKCAUyKrycF/VQGxls/g==,iv:yLySHJd/oRZvl/JL0yhgvTLNUL2Y2cyGJQqRaWQBsXY=,tag:RMB2NRN/v4d7fyWJ7pC/fQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T2E4VEV2UkgzYngxakd3
            U0FVUTlIUTlZRGFWUXM0YnMyWS9IWUFhQmhVCmU5KzcxUWxUS1FpNHFvQTVjVlg0
            L2VDOHFrZlMxNDJkYWlqR1F1MjRSRVEKLS0tIHdkN3dtcEhCY2dqaTVVVXhiOFRt
            U0tyYlJvSDZWbWxxVmZGT2V4TkpYMEkKMJjcpYbUo7d4+AsWpWEzAXM3Ll2JlZk2
            BguDy6nzLoMoY/VKSkWAawhUim9rZiX5NesXAngr2cDduQsB6pFn0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T03:32:13Z"
    mac: ENC[AES256_GCM,data:vSbBCCwKhYwepJrsmEqFy7aOgedoahNhf8kOjsu41Oh9BY+9bADPg2j+5Z6LClMQDw6BpjKZ94DwEtnTTWiyxcQuS2fqwmsLfae8fypft3wA+KbgterLS3egxuBHtPo1bNokuGSvgXgs+a/XBqkbbY1I0kRbl/YT17d39YvjPoQ=,iv:FEBEGyp1GpSIlOFGnwIvR/Y/R6r2HRZIDaOCW2ikSus=,tag:OnUCjfDuMS8a5vzZQ1SHIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
