apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: renovate
type: Opaque
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:PVSdQSgV0N/M1YS6Q+ZX/2eW7DwOqZf7FCEzdA1iYV8pvSYCV18BhcoaLvF3W64igf9Zx2rPODiu4lQS2+L6n7GjNGoIj8m8Ac3ulP51vgiTPs3Dwt0LDLyDRbqg,iv:xm7avHdjXVB3mmBghy736NZmtzpgsmX0A1yhKTGVQGI=,tag:Ni8c4DdJsYYsRRQFpwGGlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4clhPUHMxQVluL0hmcVgx
            RjljeTZ4VVZBMFBUTi9aOUdEUzVzVHNsTXhvCmtMMjVtQ1FXd3kyS3U2OWZmK0Uy
            K0M1alNuZXpDNGVTOC9BYWNVUFhPamMKLS0tIHhrTmZIRkgyV213OE80NmxXV0xl
            dm10SWQvZ1FWY1VkUjVmS2ZoL1NNK00KvSJdQ9psh15nZ/8/oTNWR1gdszVppcRN
            8fxsrNCRz4uApA2MUlt6cIu7YOFCPqUB9IyIoMO3ZbfLRfYMWlGUdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T02:52:24Z"
    mac: ENC[AES256_GCM,data:KA6WVA58IOSlDyetnHXHWjPuRT4nN0KvTNOX/lPjfGXK4Iy8hF4M70nMuzIeT/ZuvVS8y7m6Nl+/Ji8boESeebJISm3rbbmoIatZ3C3O28zC8Q+40RajhnHzYIEVoWW6MhC9hEjcMZVjSmFhl6eOvFXZWU//c9oRwAoMlOyCuPQ=,iv:vVrcBjGv1sbujNbaGxEoUj+6v9Gs/vDkk2gRwjOOg+o=,tag:4km8CJNjKi7Lk5FD8nU7UA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
