apiVersion: v1
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
type: Opaque
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:vV2CC2+Tbi8i3a14dWcCFBUrpwpCDJsV/hnKPNBHdX4ZU+0S4hI/B+QRCTFNJM0WyIyiTvrIu4fAreVghITujKBVRI8l/ahPVJr1Zjbbn4igTIaEUwXesQArjoCbIBxZEFZ7TqJV3rJ/hBye/CZBdzOmznfAGGu+m2h5N5OYvou7GcT3YMsNlsTX/JDCWHiUz//TzcSe5XZMWMdRMaTzK0Q=,iv:jdDek6I9JFW9gPJ2glPtTmmC9V+MUfoU5xVtZCirZB4=,tag:KgYO3xUOZJLZt+aDieGWmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNXcxbEZPVXRMU2xsQ0pL
            d0VXU0xxMFRpdlBrbGkwOFBzWFA4KzZzb3lBCm8wemk5UUVvWDlSZHdoaElvK1pu
            ZGtWamorQ2dDbE5SZklOdVcvL1dRamMKLS0tIGcrbGloVlcrK0V3N3VFQUpGNDgr
            anhhR05yOXZUZm05N2prUWttRThTZGcKF/YahENOW17xAbBYHpePzkhd6KNJ7lQP
            lC5zUSKWgmBs5NDlbuZxM+qiUTqAOGughZOrBhNyovvozXt16+NZTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T03:34:45Z"
    mac: ENC[AES256_GCM,data:tRLI0lnp1PDx/jfIycmVCMfH7SSeB6CQAlWVnYCFB5PhzebW8xF5dMSl64x4J2nT/DtBKtw8U/KkklENckBdD33T4koUEYqgH5UAlH+T/p+4hmhhDee9rZHwAJHj/6nmbQ1n5MIP+zgOraCCUajhJL2xgjq9QNKjvBXAtkeMID4=,iv:t7RB4ai1cnEBtnsIIj8LKc02+oh+HsLG37XcG5YhZfo=,tag:xmntvY20fYn9kamQRrrupg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
