apiVersion: v1
kind: Secret
metadata:
    name: infra-test
    namespace: infra-test
stringData:
    password: ENC[AES256_GCM,data:woZEA6C/RFlM708=,iv:7NANo//nAzJSL6wIjMicreZwyLmD+lZ3ivMFJgI1PoQ=,tag:baObXcqhFEKUQG1m9Nm3Ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVVpEaWlmcHVTY3k0TEQ1
            SlZnNEF0VSswbHMwS3cvMlE2dHMrSVJ2UWtZCmRFdVRYeVZwc3l6ZGowaWI5V2My
            Q0FEVjhOU0FkMTVjeHJENGoySFR5Q28KLS0tIDEwVVhTSTBJQ1A2K0I0dmNyT2Z5
            VG1oc2w5WHBXNDlRdTVZTEVMbW8rU0kKdsD3c2dWrM6eil2EP7PHTJTmtedb/42t
            s59Z7xvnp0RB9m6RQIXhxsUh/YX2ZfA5KhCW0H9/T6Mh5vuBU/eZVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T02:06:59Z"
    mac: ENC[AES256_GCM,data:cUKaMu5fEJMK+aIHZSpXJuOAc+BXbxg5QaZhVE3v6ddJ5zJNd/J8nHIMsR0G1WdUrLXl6NUzUpeVCjAZ2D2+U56NINok4YHUHu3vUdbLk0wZllXP/Cj3K8RAHLBw0ccHCKDRNstcy5AdCed8bZWg7IELE+fR5FS4Cf2S3HqaF8g=,iv:RgQtV8TeZw01dke5inc0ojvz3iQfBDXEKExI5XZx1Kg=,tag:o34xzpEIGxSDCahpX8d8XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
