---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbootxyz-config-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_PATH}/netboot/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbootxyz-assets-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_PATH}/netboot/assets
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-config
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-assets
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi
