apiVersion: v1
kind: Secret
metadata:
    name: talos-etcd-s3-keys
    namespace: kube-system
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:UX6CDHLagv8Nn1Scztxd6zB9YSxrLjeZw0Idr3YQV6S/F7d7dNyZzQ==,iv:hjr2ZCo0bp1Tj6XJy5uIGugCZ3tfMca8UBdazgLSJfA=,tag:A53Cr8DxuTvQogB6Iho31g==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:EbLbiU08nTrD5XFc6lAYHH4cuYynOvGSybV33+67L067U1wH+SI/pHAvlJI=,iv:W3FZgJ9ye1vCLcBJLYCCLdurG+Q4vd4cKDjzTIVkm3Q=,tag:CifpCJAQIHTBR4nDleaQAQ==,type:str]
    resticKey: ENC[AES256_GCM,data:a0Mvg1YZ4Skt+LaNqqKH1py5/yJKY6vnFrcvBdE9v78BLQT7gUOcIKPC1T0=,iv:OnT7LENgF10vHyESokoEd8HtMw1Zia0Yyg9w/KSLXpE=,tag:8Te2A8ky7JjKmHj+3hHgLg==,type:str]
    resticRepository: ENC[AES256_GCM,data:XWeWe39YW0VrucEibzAfTwklssPb44/lkHH2FeJrpzSacZgBiAo7K8fRj8jeQCREoDF1M5YLTjiKvv2HLB/rXvAcrUa4p2rt5dfkoFEEXYIX/Bhj+7V/fC0pVA==,iv:RILLibS6fkBzMAOd2B0kaaHn+CdYMqFY7UxCfzer2oI=,tag:cSTG+VbsrfPlZ+OYMe4qHw==,type:str]
    ociRegion: ENC[AES256_GCM,data:zg6eSZPGXOR8L3sW,iv:Td7nuT8u/Xq+dG4KNnnD3ZvfhugSYcM7giDVfQ/d5r8=,tag:fXhT+HEEEffTGMgUQJLyhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VHZ1N3pSNjVRbkE1U0NJ
            OVQ1TVhBMUQrRGozcVl4MUVEdTQ1RmhrbXhJCllkRXlvbndxTzcyajNuS1BBYVlu
            S2tYWkUveHRpRzRiSnFXNW9UbFZHejgKLS0tIDJHb1JkNTBIYWhsaStoTTdnT3hu
            TWFvOXJLR3BaZlFLQTUvRjh4R3plakUK20Kny6HQznUX5sHZczOCq+w52hN67U7T
            29LQIohCvA0HmucBpYopLaiW2idsGp3ZYDCVBGe/ABSRtlTcqEOVFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T14:32:12Z"
    mac: ENC[AES256_GCM,data:ttvRugK2s2xukx/cAe5rdCR3pJlwIr42pC1gTJG8LYRXqpnk7PSjLyRL1Cb5CVsbUqS3yyfVpZPRrhufbgOFgHR/UaXl8ZcEeL7JXbH+49lxs8Zyqw4I8ab01Zs4H7X7BoX9LJJDo7dVnYfdLacDxc9zmLTab9HfZ8DL9unAHc0=,iv:Os7sdOtTvicgDmeEgh0f7DsHY4R0s+dNDCXSn7ANmwg=,tag:LCYs7kCwUzXEu9DyJjl7WQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
