apiVersion: v1
kind: Secret
metadata:
    name: talos-etcd-s3-keys
    namespace: kube-system
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:eqQusjwe5tHM1CRwMPEp85cKIjrdc44cLpwBFWRGptJfZdfA9Ad4yw==,iv:umYDT6XphseIc+2hLHRVHo6XzWFRFcrC4SV5r9cT6+c=,tag:Tngm9fLw7sNB2Efw1UPMYQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:ib2/fNQNy5+HZ1rV5owPmqGaCQdoCXuLyXiwLrD2R8DhEZYEQxS9qpTeoAs=,iv:okSG2q6FEjzNlf48JYQPdiSQ3nLm4RkZAO4a8l/OIEs=,tag:3FugEA04XdPp2q+fhrhrMA==,type:str]
    resticKey: ENC[AES256_GCM,data:R+inROotnSrGrVMbROy8U1aLnp3DgTzC2j2i0WIABVJHtu3kI6t76IAwEqk=,iv:nDKveKzyknGpyzZaZ17exvUgyCp4LpUs38e9KjtjfPw=,tag:CoBZh0MRR7KLp4luHEUh+w==,type:str]
    resticRepository: ENC[AES256_GCM,data:12xy1Y1GSkaky8dwoako5hvsQmr1WH55M47u7sabt6wwwQYyESX76vC/BcNi8KFIQ62Ah1Ma9D1Ewv7Wr3qka546wY3HZvL4mJcCPw5orJvZhshSKS2Ajg9zK3akcCMi34mSdA==,iv:ZgBt0gg5xX/Cqj9H8mD2HHvmj3jz4KsYG4M8eC8jWL4=,tag:WzwhPWGvbDhyv5X9JfmtMw==,type:str]
    ociRegion: ENC[AES256_GCM,data:YXEvY1eLE1LPxH4L,iv:uewL1+lZk2j5rSiR2ygx7KL7saGWyZVXNqkMiJLJipo=,tag:VKPQ2oxDgyDjC6FImH2P7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TTVXQWV4Y2lrK3J6U3hV
            Sk9YK1NhdHFvNnBpWFZvdUxFTEhsaCtqZHlrClQ2RGhTK1BPZTcwS0YvUHYwV3BB
            WXZhaVBmOE4rckxESi9aY0ZqYys2VTgKLS0tIEd1Y0JGb3Q4VGZ6NlBaYTc2cXR1
            cjdpbE1OY09YTW8veXRtTU9lV2tVRlUKa4pwbpCM8Ix96OnK9RuuOwnuXFOv1szP
            hJO5VxNPIFvq7S8u2YW4sDTd1KD6mXC8PcAvOwGXewFW2U4Ay34RnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T03:07:44Z"
    mac: ENC[AES256_GCM,data:gxMoDqejgawUj238eCXlVxDEghS6XkBNvx+gw3DCNhucCMx/31FSoco8EsFvT314NTuf4XKT1G64EkwjDyWiNNMFMkmUWLEyJ6YpC48TnQRxEhQBA/PBSALmzsn72AfXg5TM7r+EYpAGUzWFbFz/id1+wYFgfCzOJgDgPn2KKP8=,iv:DqobVaJuodR70g2ep+DoHjzkAF6zEVyJOB5kpzW0zog=,tag:pCXDztkvKvX9zqKiQcNcuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
