apiVersion: v1
kind: Secret
metadata:
    name: talos-etcd-s3-keys
    namespace: kube-system
type: Opaque
stringData:
    resticKey: ENC[AES256_GCM,data:hslhFd4F7FvWpTnaH7h74WWtYWIiV6JZADcuwiolX7nJ16baoBD1GWkLY5Y=,iv:5AFYewlWdsvc/ZoKM6HzWo5HSTyNtCmgAwUNDPBDsj4=,tag:552h0N61ezhq4fdrs+A5Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dFF1c21wN1FEaGdOZmwv
            a1Q2YnYxRGJIYi8yanhPL2lOMXIvMTdMNkhBCm1GRUl2TnVBSDNnZUpZa0V1R2ht
            Y3FFZUQySHIvbkwvVXpHMVpueGZOUDAKLS0tIEZQcUJrNVFnd0ZqS1A3YzVCSFBr
            c3AzcVVLTUkvbldWODdaZUs4aDdrcEEKoF6F0y9nG/AeRpw+qp4ynDcVJN/OU/Mh
            xq2DEUz6CzKF4OZqVVPp4AjErljEOcbTAgbAHJKlnnC0gzm58Em3aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T04:28:22Z"
    mac: ENC[AES256_GCM,data:L/DuCiTM3+RexHefLg4xtcGepXEzXCro0kZjK9Cr7b062ymA/WvavJHNCkFLVqjYewDn7W2AlPcwgVKBqiVdbMPatg3E3m2+vDEwkcD7n/3E6zSJI0kcu17fnJ01IdF3Um6EJ2KuFV4asKP5twQWh9+o8QGP4WINE13BLmUyuao=,iv:v1dOevK6bEx4QT8CH9SunctozF6FaIHzVTSY8petWbQ=,tag:d/vgQ8y2TUC4p/GDFuGXWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
