apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-credentials
    namespace: iot
type: Opaque
stringData:
    passwordfile: ENC[AES256_GCM,data:Wd8ovWCj0Aru1hQOxEAWkOyOQr9WCTeLN2u55W2iYMDtPtoZ3SNUI8ug58SkhS8JbhOFxqlzEogDrC2++3piQLp48R7lJZ5Vw4E+JmoCeuznf1DnWSNCOVESh1h/KzEHtSF1+RS2syQXbGoDpceXcOG1+acl3Nala6jYya5j7jzj76WeI589mXp8rB4hgXzDT4ZFoCxqgTkC33XZrimzWUcPSO1FSNChXturBK1Uq3rh2nf4nJeBGCYnOQ31gYrVi72vb505SsRFv7BDJNfD+xdknGShQti0Gz5vTJRuhFFcctyWTgdsZnd3tdm2ey+N2ft79k8QX1CqtUw3eyMvDYqddkMhmwpUf5F3ltHljuTWAIfeeNXP3eFUjNDsAY+c79wb4c/79C3yLFSdjzN8unqVEk6Ia9Cb50Q8+p//6SlpGzERS2qUH2vnNyU5IDCnWqaX4V33YuH9Gi1FHJTCLc2g+XgCO3GGed/D5f5yGIzce2TzUaIHd0S08hMIR5P34hDpCAYdc1GhAden7SQMqW3AW/EhkXHOobDKZ5X+gyVU6eRowRF7LyCoHGuO7A0AUGWyKPpOQgR9RemuXJnfgLxSDF0p4I9ooI+Dw6UEeu0W0w6WHN1+rvchXl3QOiJvGUtNHL36CUqcJQ0vNttZIZzRRC2pv3U4kO3k2+Q+AVcG30aE980dV0dEex/TrNVoNUvzhzHVrglNw3lr1BSejqbSVDjvEHg96Gb+EC/3OQgmWB7lfGKbrztZ+mr8slL6YZlam0WLar8YWxMrjrR3IQV3r+xly7xEoddIGM0gNuo0/AAbNe3nmYadNTDXr0kt6IyIvgPE/r2Ivruj4GzbHKC0+H2mYNfh4llvHl7txrKYIF+yPhAUDgCQyiXJkYqUHM53IkuO4A3atWET5uGHiPFg1+StWz9WZQ7Ze1pNo09NuRSIMJrdEKNSA0gMj78wXkuUS+IIL8FhL5fKJy91Zq8IdSvVB/FWBVVMtqfiDWymqyuSjoxH8nT6eWaduwEjih7lq0iKfdddq6eHh9z1HGADs9Olbu6qdciH66wZbNU4nMZWqphadeKA84OyS4zmjbpCpy+1gwPpGXt1naijU/gqnSIIMhV2arsN3Xl5a19o73QCLWSJDdeluLBEtgddE20h1Of3XJAHcajHWFhJWYEDXXtcOzcIb2eVQx5zd9r4dEpHFSFR2VkocpgKMmZlo5Fl5O7u+QBzFenrGFcWSHygA6sUVZKMREemoJ6YM+kc538GXRmBBRa2b8DcRnn9TF3aE9fjxpWXmJjIjxA7EmiLGOYEtRm81TNSzsGcilaAeTFpSz6obSsBsftEkzkXwCi5SgkJ5bRYDfZUgSTg9m1Ss9g1gQludEmC2XNpak6MGcrbwAToPAY8TtZaYQf2huoLSFKEmUCcj0vOxR+v4aGVL8M6DEoXbgwrS5Nxkz0bGWFDqlmo4UxpWxlXe0TU4T0ZfRYNHA+5deR6oHjwZ3Xs34s63qWa/BOKk6iHQlg0VaRBlH3N+YgmZ8bj8kzaRAOv7vjV/F2Gw6Npo0Q2tyT5Yl0+FVjJSE/zod69RJm+9858ZV+ZxCIX8GlmN+4TqpWBJ7ioygk4VPn2SLzna8eLfD/xzlNv/QTO1i2dK+eG+jFGnCGjN9hAQwD0gdVLQE5aZgeNkT2lJSMFuNZHjOvx6e150/mLESs1d68coyUGUIzry1r0oe8UZPTUb/LLI17TO1oRAaDopRzkxrsAHgCnZSB6niYNCuJKloHo3t8eSKQexvhhsU/IZXjUC7cJ+FNaYeGFhjZfJSMIZm3K0oURlKNXuu202ghQByZJXKVAF9JiEpt3sJwCCQr7oPcYlV+Dza/iBfQc+obII+GdspTc+PdPHjB6wvg8hSuz7ng5Wf3SXVLNUANLOsxz3TL41oSfnescS33g/0KIpJbGE3jD0KdNf77xCTOFr5s5OlgGpmqQTNg6umxeY7XiVOti8qNSPU9P3Cup/0vZ+7qvXucg7yi4+WeJmDRDTLrvh5YAyh8w8bikmgR2uoaFHQfm8DR85aIHeOI+P8lOkWD1lag=,iv:TvnFFRyYEi3lP98fpvsrtQbXjqlUWbvxJlqTPowypaU=,tag:w358AojTWrTPh0m6CCTY7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bnYvZktrQy9wQ0dBNzhR
            R1MvNi9IT0M4dGlHU0JvNWhRc0VLTzQrNlFBCjR1MGZ5YlpCcG9kakR0SWFKRmV5
            bkx1aTJ3NC9XWm5kbXphZVhhYTB3N0EKLS0tIGgyYVM0SkJmUUVWeFdHemlsTm5V
            bzRxbWplcXpON1B2VTgwb0poNmd6cXMKEJ4M+MT8rU8FfMr9puCGWkO7/xaxQEwF
            SuOO8acZ8Iqy4ifawuERJKCypvjLzqOHy4QoyFtkJQg6k4ng1ug0Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T03:38:30Z"
    mac: ENC[AES256_GCM,data:+lUgv24GzxFbwpb1y9QT4d85dQYhQ4W6DVt9VkkoXu7x93f8Vsb9ccTIIN0bqVIBoPPOuWhws1q4fTypbRdZNYU2rX6jnojPgD2E02aDhZ+S9P1Rp6huJRB/KTPvEE0z7OtOUPiTvuNzZ7WVh4dPRftCNhmhfWPsWnKhDHmHk1c=,iv:Lor6C/GTsxJjHN15HxDVyAYBOiO9N7+JspdLzIJL6ec=,tag:1lCzdLUaz7k8ueoXgl76AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
