---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |
    persistence false
    log_dest stdout

    allow_anonymous false
    password_file /mosquitto/config/passwordfile
    #acl_file /mosquitto/config/aclfile

    listener 1883
  aclfile: |
    # Usuario testuser puede publicar y suscribirse a todo
    user mqtt_z2m
    topic readwrite #
