---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: iot
  labels:
    color: blue
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mosquitto.lan.${DOMAIN_NAME}
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
  type: LoadBalancer
