---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # image cache, history DB and backups grow over time
      storage: 2Gi
  storageClassName: longhorn
