apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: oauth2-proxy
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Aqe2e4JMgo7c9wLqawxQYQ2seab4eu6TspyBdbk6bd40rO/Q,iv:P+S11ysrCWzgcrlFCsALf15kJWcBrwwLYETN1WhWrZc=,tag:bZ45qlkBG3pUd0GGAtYRWw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:NQtrBZzeYHURnvC5+BKeXWA50vv3ZZBh1y74yWnHSfY=,iv:dnFR0ujdG1huVWW4NWbYgFDiRGVqAK+5Yb5mzSEfWbs=,tag:WurilS+4KvY2pvbX6W62tQ==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:6vzmb7vz+eY6Nfmfqd+bff5zwvI2ncR+r/e0bMN9pAY=,iv:gDJsYakfZXfiDnMvwCp9X3iqcfIpZexmiSxuP+yCPW8=,tag:Jz2T0IFKkPBVSRsM7T8l6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdXJRd1ptRU9kcmxnMXVW
            b05oU2xETURiRUd4bTF1dWJNUlVkUVBwQ0d3Cm1jOHVUcHRFRmU5RnhQYTB3aWFz
            VWpFMnFJU0xtUS9RNzBXTW5yRElNbUUKLS0tIDNYT09HeVgxUDJtK2RJTm5pN0Ix
            S3NRSWI4TE5jZzYzOHZIWWwwcmYxb1UKfEzgDETzyo1KLDaaPK1Zbj0MWlfWlpnb
            fFlIokK/P8fZ700LGdn6pYU0hWsA+mme4dwtt6hFV+irMpR58a1DPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T02:24:52Z"
    mac: ENC[AES256_GCM,data:4VLfHHS4S1ZZ5ZduDs9NbrsEIUb1uDqYxGHb7DLE3t2mCEA0PAlgspjZ82MAJ4l7gq8ge3kNxH20Kioy204liSp+gXOrR53M/AavSKeTdW8A+muieR6SXnY8V8DhA3iMLp/NICUdz3vA5zwjwXMtpxKOzG14vaoj9acz9nf3YKU=,iv:T3bPydS9uqUc1BED4SECadIce/QBxa8mJ/0GXn1u85k=,tag:8S0NQ63ZthG9xnyM/ywEiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
