apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: oauth2-proxy
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:ZaukIIMCzFs8mEVyWaX0ia4LQT+xYA/HW+uQYQ/XGJjdDgx5,iv:CyxGv7Z/u325tPWOhB0FikyMSIlg2tIWUpBcaPgF6Bs=,tag:IAxwPbsYiFW6LAMbc2vMHg==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:GM4T+zKqUx0CHtmEYHa35uDzqa5q2ueOYhxDr388NUM=,iv:5OCjCoUvvvDXkrXBDyL+Tk0baTO/H089plOICGrUgI0=,tag:PmguxbguvQYFMAt9CPnrSg==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:3ZtSvFiLLF6wMSbcE96xa6CO5+pw0fmmVWX/0J7Bae4=,iv:oZu7bUWuBHepeY8utHzPdi2EyQW/ODsDJBcRVOBzC9c=,tag:JAByiDnHTZ9DLHbZ+uxVww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdWZiZDhNNGJIRlpYL1Vp
            UlpXQUVpY2JoYTZ1MktXTktjNVhpQ3pWb0JJCmZzSTJsb0d3em56Sm5NcW9HNUhT
            OXM5M1o2b29MVjRDdVByY2lXSjR3REUKLS0tIG92L2cwVE5veVYvSFgvL01JREh4
            SEdRZVdqaHlQM2tQdGRNVHRrSVc1VVUKM2naLU/9gafGxSmu0Lf12vjdX81SpFq8
            TIG0T/gynd4a7PP1yMwR4GbM47Xl5lg2XrKALeu0JGirzQJH+I4GEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T03:46:20Z"
    mac: ENC[AES256_GCM,data:ie9tY5RgsKJVu7u9O7HKQjyyPRfLNt2NHUU8NlD/GF2mpFPtstv1K6NfOsPldcXsWFdvTWeRg0iD6YjCwCBU2hx1MMRImIwFIswHsNSnLgE32muO+Y0b2FVI5hWf3MN0qUomVEIjVN2qnAy9POQCx297+fra31DHHNMbX9JfcUw=,iv:XF5RW9zwhkR+1BuqPxEHtkiTyppkwM5b+LH+LrumtiQ=,tag:xx4MQH/6fbPPE8wQQIkVog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
