apiVersion: v1
kind: Secret
metadata:
    name: mqtt-explorer-secrets
    namespace: iot
type: Opaque
stringData:
    mqtt-username: ENC[AES256_GCM,data:8SnUgRN7y/M=,iv:ewK6yHxH4dxBDk6aPp89O8R3MCPYmmPqJEKZqyAOviU=,tag:B4rlRRNaM1wS9eMIQRZXSA==,type:str]
    mqtt-password: ENC[AES256_GCM,data:rlaGbEanr2gZLsAbh14=,iv:q7tpUflbqQbjVmb6hrRKiNhPNMNotiDjxie8g658gBc=,tag:6SDuVxd6c00t94f60x5i2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NzhhbGFsYXNGdjFLaWYw
            Z2t4VHdoR0M2RGZONkhWb0hZamhEaXpMeWpjCllOMXZyamEvNXVOTXJ4cjl6dUk4
            b1NHeUhMSGxKV1dhZkpMMlBsSkV4WWcKLS0tIExvYmtSeUxTazJzb0hsTTdlZGxs
            Y2plSXV6eVNrR3RPa2t0bit5VVNDNGsKaiC+8yzNnfKgV/FNS5+1oZGWskjw7cuN
            TILFDt+bo1ZNMa0f59kCQigoq6C0rMjlBR2qV6OIBykg/6fAsO8DXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T03:58:36Z"
    mac: ENC[AES256_GCM,data:ileGv1UgwqN0ru/XxP1EhvOScKuhqBVZcTZ1ZXnGmHKMAVbBlxXe8JwXsL1K8yr2o+hRUunm0Pp4ryWiEYctaz59RevC0kR9Qnz2l+8Q7sUIGM4T667LxQn2Zayx4SzPZHamIVPxGWZ8Lk+t5BX63cpacl5Rizec5BE0qsYcCuI=,iv:h6a/HdxDVTbPHKHMe2hX5ix1s6u7XBFXTwW8lDpqotM=,tag:u0+/jLMH8uSR5dsHppVY0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
