---
kind: postgresql
apiVersion: acid.zalan.do/v1
metadata:
  name: psql-cluster
  namespace: database
  labels:
    color: blue
spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: 2
  volume:
    size: "10Gi"
  users:
    # Creates the radarr credentials Secret in the arr-stack namespace.
    arr-stack.radarr: []
  databases:
    radarr: arr-stack.radarr
    radarr_log: arr-stack.radarr
  allowedSourceRanges:
  - 0.0.0.0/0
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
