---
apiVersion: v1
kind: Secret
metadata:
  name: radarr.psql-cluster.credentials.postgresql.acid.zalan.do
  namespace: database
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: arr-stack
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: arr-stack
