---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: database
  labels:
    color: blue
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgresql.lan.${DOMAIN}
    external-dns.alpha.kubernetes.io/ttl: "60"   
spec:
  selector:
    cluster-name: psql-cluster
    spilo-role: master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
