apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:oIANlVLBGxPBrVF9RWzO4K2eYqfXixLb0u0VNg4GBqeyEyqfaX0bJEOVHipBP6GQ8TOkGTcU/4t+KFSMEltXq7TsEZC+KpUsox0/X1G+vY2u/1ObWcCveIzF7AnoUOjfxnUMInfZrXTDnfAQvxeAylu8H6nbOAwjf6FFcUhG64i2ERwW+aBQRfhIx9dwEGwm3dI99o/SQTcL9Lng4+Z0uiuxz9aaQMdJKFHgPVaX,iv:3IT5pkPfontyc8AGdLr37qT+Wa5L9hvCZUHUiZ4WqRw=,tag:MADnPil9cEnocQWTQVbY6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbGY3Y0dZZTFxdWd2WDI1
            RDR3WUViTlNTN1JHVTNsZnNKVjdGWTV3aUZ3Cjd1dTRnbnc4cDhrTUNQcGV6UTdR
            Z0c1eGltQWtZZWdYeGQ4VldwMXRvT28KLS0tIHJ4QVJhRDZnRE5GU3BTRS8wQTY5
            YXU2UTlENkQ5UCtlZGE0VmlYWmcyekUKRIMA/GD72L7JbxLi8sRZRatKg/sk7UBr
            XSz73rWdVV9RMQ8wyGRxTeOf+ZElotU2VPgicCffmb8acZT/BsiGJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T11:57:39Z"
    mac: ENC[AES256_GCM,data:YberL+fthJXy6nKW6j3Zhw6dkNdjcgB4/N4ybYSvuWhrQQs6mpB0tdjuoicWLx2jqYH9MeXS4qV3VPca8OD9CNCJDJKpZDbh8HSL7oM2Gjmkai1ONUYivzjpI4oA/LPnfKmdz16euIJN/iZd480rqsNxyyVtzIxAWN6L7sffyi8=,iv:clVIscFY3clI0P+SNjlB8luWv+8YZzqMRSPOyKdj0OY=,tag:peIRwbhPt/XFhbZ9PIiPOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
