apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:neH2XSHpKlZkLU8Ip2FswpZramDnmRF7MLTbtdd9IiSiPvfMetQU3TbjQoAqLeNpJ724m74yOw+HUWDGOIDZBF/ks3FF5oH1K6EXqOfhWq83kjr8jGqJEzr8L8a3zwoud83NqQVBQY+uwwGiXCCJZ/Q+ZqXWSDQSSPAJ81L5LXuDjojQg+Ppmd6jMzLD/vVg3yUC8YRxhpcZgtMKRUgksv1KrDtKAel8GOmaSZTQefLPjcpKkOW9IdVJs9Q=,iv:NnnDsPmzIta6Bbju2a/EguNxtSbbTtbLqlm4yEN0SRo=,tag:2T6A93yO3O9YmVKQbDir4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT2c4ZkhPdmt6V1B5UFQ0
            bDhSSTZzVklkNmRwdFdWRzdldEUrNjFzUDNFCmVEMjJHNGEwOG1qeS9TNlR6bFVB
            VHJ0VSs3ajR6QTgvdUFhM2dnQWtrQVkKLS0tIE51QVZ0dlhqZkFLN20reCtJS1Jz
            VmZOV1A0bXNrZ3ArUGd0U3Q3bUVNK2sKSMpzIWUZ/IDflmsXgHebxOZTug03Uu3q
            jdwkNv5zxrSc7GQen6gsAsByorGmztYqEq3uD86vqLhGfcDuGessfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T22:16:15Z"
    mac: ENC[AES256_GCM,data:xoV58HQVeS530FnnSf3j32XJgqQkkgFJdOJk4SlkaRgj69UqfJgFqE8G3R3RVO8k0bWpTlUlp2KagY43ol+EyHFwT2kWSfh0FBYXOxnvyCSD1pHRqB1sq3yHm5tqalGbEp3X1iP3yHYC6BXlpjHcwDoD6VPteyr3fYxGt/XDLF8=,iv:S5v55/dHmtOdH4g2YmEMAFsFo85zn272nUR9idzOtBQ=,tag:LwnPVnKBGDK6dBQ3ccbDWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
