apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:8o8Jz6IUcaCtA9jxmbCZ6o1vrqwm1nwbg1ZFgjh7fRb/nFWpjCbgBAXefeeMYjUcruh1lCeGxAkFr0pUv5gz9pNWdBQOpwrDiH7FSJAn1jCoc2vgA0oDZDNpNDKUnpiKCtZnvWL8VMcNtIfQO2sJeOMCOGFoZpIt/71z7UTy1ybRfzrDMYEQ47g7iWPVYZlKcRUctorI1mfoB4bNynuWcUfvkIudgMCc8K8pwVhjT3QQYZpX24hKHA==,iv:aLkb9gebTQS4O8fyZPcPg5TNuULqbVqIK00N9umjMJk=,tag:Rfn7z6r7JmzOSeoTdOcHnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUkZndS9qL1hpUDVrS2lK
            UU85NnhHOTlGWXB0ZHhROEQwMEhpdEMrNmhjCnVOQW1EcmVSKzJpandZMnZoMXJW
            Ny9paDVML0gxZEcyMHBSa2ZVQllUeU0KLS0tIFhCK2M4Mkpzem4wY2xzeXR4WXgz
            bllSSjA4QWtDZG93aVBIeWlzaTFZQ0EK/XTuhrFWsAXVFdDpXrk4fqwJkSWSNrOz
            XWnP2dz7GfSeMC33A2FuOLqaF4VrzEi4fxrBkOqHKSF+/svLwE6Qdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T12:07:20Z"
    mac: ENC[AES256_GCM,data:+8luYSNLUnS/FF6hKF/BTp6wN33duaA5SyvL0t7b7Y+4/6BH/BMT7SMoa1RuskyGKATO2SVl7UtUvG/+c7onal1eOjPGWLrC+max8qbyN+2PwuyYYFtXNlax2PPOTJQWH+1wabyx+gFyrFXuIU8eZvDUdYQ71MvXHlsnHNdR5fg=,iv:plaEwB7V8+bJn7FO2DrdbDA3grsm3BMYnmsLfdnMVAc=,tag:1kjnbmrW+Ks5u7PIJBcWnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
