apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:kCZoGPbwCG+cmJdV5WLU7wnNC4vvtSRVhRXgSKN6mQS5NPInRRdIuEivIa9kqgBjvDMFWuRp+mnvZXBcFurK1XqnEYJz1nqZ05R6Bgjxue9ZuQoctoCTzRYlZB/bUA5e3K0x2XVsJnmAzHvyrUU4Wbuux/34dAVP7YxfVIH1cMleDtfaaeLjSQInYhWsC5Hm8TGCuaZPb7YAB6zu33Gc8LSkABHKjLkvrutHV4a4oYHrqoXI,iv:C/CRSxxtQ2edS7S6TBvE4GfBwNLrpgtyzvvMZN9qMyg=,tag:9f3tDkvCogqH/ygF8wN18w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ1ZJVldnR2dWRHMxeUts
            cjZOSEdpUjVISmNxMDRmQVhzTjJVWUlrU0c0CnRHVkZLeSt3T0FwbFpBb01ZU1dI
            ekc1eDZPbC9PL1BoWCtSOW10RElUTzAKLS0tIDlUV0UyWlV5T1phbTV3ZHdMbGxJ
            MG9yM3JmRGhpeXBrekFpT3VyWGhSNU0KOMlztko9X3iLnPHKQo7eXMdFfJMh3fbQ
            ALRT0Ygef2+hE8X8RUhijkw+OtD4nZIQiOWBuvD/k7xVZSs6xcs5ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T14:25:06Z"
    mac: ENC[AES256_GCM,data:8i8w/kqPtpY2ZynBEtKE8sxfu9zVUKYErvTFiVapbcDobVn4cjaqZxvdLnaMYzW8Y9qF7QSFFD2sWYeQepOaZ7xfwg8IcF2tsuTGnDmnPGXdHe/7gNdqspHPjQbWhs0Fwbf+i45h+rgz394zj/8Koa0otKzSPlsyHXsvRFJaHxs=,iv:2NfTylqDtVFXkWZZ0tNholsfmYD9GnFWxrGUwJdcw5E=,tag:ZbYiY5fUmDoWqtf7g9EseA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
