apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:V6f2vQef1OuuWpIoBEo9GSbIegKhduk/GjcUaoY6FCNxoP1pDurBSpXJaVLSWMwXqbbr+rdItlV9Jasb1tWmwf1SqMFR5eCHhLFSCD+xzX4OzAyMjHCVT/+XvT9D53n7H1yO62vjQry8eUEwm0gRQKXtS0mbP+WWGUoZQ9LanvcYrGCTc9+oZot+g2Ed3OurjCiQoRzgiovNCHWuqHMLgerIgZClNjHAR/8=,iv:/nuV35Mfav38uO7LUkFYXymWGKRRqK0340UZW1B83jY=,tag:b4LSpfRrKqFdHPudAk8ceg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVm9iQXpod0JoRGNMMmt3
            VWd5QkVnaE1xaG81T2lXOGJBWTIxNCt3d0VJClVEYnNZd3NwL1JZNHoxRXMvMDVw
            bmdqT0RyL2dvVnh4MmcxQkJ0MXNzeEUKLS0tIGhmWHB4RGl4ODRxc2x5S3pLMUlv
            WVh0clNGcS9HNnVnbWRia2dJQ0xWN1kKTcpW1SqMBepsXcOaFU5hTiFcq47hVyAC
            MTZhay6FrNu/lwGQEpnlulnYVh28H/KvVe6d9Pm42DGeRFIom5GdHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T03:27:56Z"
    mac: ENC[AES256_GCM,data:++BVPpbzatEsj+amafUAyT/vWzVsgQOgo9Vb78geHms5D+GNCUWJCT9Aa0t/w3r1XVMhD949Ffzz0adnQzkCsuUEEY1DULIu3FXJfkDvvurIg4euEvnUpLqxzPh8CXe+IDfLICFAaXaszrLfu9Er3mvogjdN3fBcuMidXlGqwUs=,iv:6safYphgjhvPo9RSuzDUDILYblrPElk4esTlFcqjmYA=,tag:8svO7OIrcBf7gcW9BgtbIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
