---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid
  namespace: oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      containers:
        - name: pocketid
          image: ghcr.io/pocket-id/pocket-id:v2.18.0
          envFrom:
            - secretRef:
                name: oci-bucket-secret
            - secretRef:
                name: pocketid-encryption-key
          env:
            - name: APP_URL
              value: https://id.lan.${DOMAIN}
            - name: RELYING_PARTY_ID
              value: id.lan.${DOMAIN}
            - name: VERSION_CHECK_DISABLED
              value: "true"
            - name: ANALYTICS_DISABLED
              value: "true"
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: pocketid-credentials
                  key: username
            - name: PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pocketid-credentials
                  key: password
            - name: DB_CONNECTION_STRING
              value: postgres://$(PSQL_USER):$(PSQL_PASSWORD)@postgres-production-rw.database.svc.cluster.local:5432/pocketid
            - name: FILE_BACKEND
              value: "s3"
            - name: S3_FORCE_PATH_STYLE
              value: "true"
            - name: S3_DISABLE_DEFAULT_INTEGRITY_CHECKS
              value: "true"
            - name: UPLOAD_PATH
              value: "pocketid-images"
            - name: S3_BUCKET
              value: "homelab-data"
            - name: S3_REGION
              value: $(AWS_REGION)
            - name: S3_ENDPOINT
              value: $(AWS_ENDPOINTS)
            - name: S3_ACCESS_KEY_ID
              value: $(AWS_ACCESS_KEY_ID)
            - name: S3_SECRET_ACCESS_KEY
              value: $(AWS_SECRET_ACCESS_KEY)
          ports:
            - containerPort: 1411
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
