apiVersion: v1
kind: Secret
metadata:
    name: pocketid-oci-credentials
    namespace: oauth
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:GzYbSFxEaM0xpAJz0CVoBcqAu/BPfxr7Ny6Rrj6sCZu+SPiOnqLcc+/2ZNo=,iv:SDLbCaL2Mor3W/BfOxiJqgeKQRRCLmO6X0Qp+CVJFVQ=,tag:JSB2H0wMrNNIa3JaIEro2g==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:2aCjDC6jhIR2Tcq50TVZ,iv:ToyTT2MOgYCYTybHl9HfVMtQa+pGenn52xgoFJDtQAU=,tag:wqbKGWxfVMPxLQ+aPl1Xmw==,type:str]
    S3_REGION: ENC[AES256_GCM,data:OcRkRSu1V+bdYeTs,iv:NuvZQaBn4vEnCFvnzNAXmC2hMm3q3VUvmZvAckw4O2I=,tag:v6C1drFHB5YWDzXKLul4Kw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:XQeIASPex4muPel8klSTU8oydFIYJNww2BUG83iT+PFSBmcbHy6XPHvPczs8sNXknNgNHUeqjX/X97qzy0dpu6x18zZY/A==,iv:2eklk+xbXdhjZ1mub6R63JshpzOhKbxwoVRglfCh1Lw=,tag:We/l0vihKAYAK4Lvsi2HHA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:yjgWICd0v43d+oPLXD7v7nUzBpN448IQvnB2re8FePVBMqicaXAA4g==,iv:esHf6UJ4F/seiTKpQmerexylWX6upDAF60JaN+i4Q2k=,tag:sXQiYtjziAdAzw2CAGpNzA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ercMVosJRX1o34cdCnwxzF1Fh0mK8xTITyfb+ScMnzgNtjHCBedJesq0Y24=,iv:ye6tLnMECcrFkgKVxhFS1AGBbrOZEuHTE392P1botAQ=,tag:/FauKvCnsS9Ux0sk0uOPrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZHVudnVhcUZUOE9WYVd5
            MEJ4cWxrejRhRmdzL0RmdnArc0tDNW9WU3dVCmxpazdtUDF3UFlMUzNuS204WW1C
            QlRtWGQ5QVBzdXlLbHRkME1ZUmd5Yk0KLS0tIDVhMEpHdGZMZEJaUnAwbi8vRUsv
            dkFQUjJpUjhreDB5Y2lwYktrdGhzZTgKoP0SbyYjLoUUxmKd+1xe8/gl4PB2rd2d
            aVkktjZgWw02MZMAIF36ZJuCdsCDrC8WpZzhkQHc/afqlP5Cm27Wyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T03:45:49Z"
    mac: ENC[AES256_GCM,data:8jFvSx+C3fDkhVKhpFkPCpEBJppPLYae69JANzjJUGihIXPOzRd2M3CYPST2vnQnlUuwewX8jq/Zv8dioRSWVgzlBhcXlfwMa7vFOFcteSmuis0w2dwRdbXFzJev3y0cfAzpPL8/4ooG3Wnz1zu5SiBOArcr7m6mP6iaZTYYhxA=,iv:QUQDfmcFsC/cc0WkhfwuJyqNmsbOH88m1x6vUDgHum4=,tag:u1pcCRcUEhn8Gs34bH5ddw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
