apiVersion: v1
kind: Secret
metadata:
    name: pocketid-oci-credentials
    namespace: oauth
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:76cBY6hufzYacJofqCswdefWa1vBxzow5x1osgN/Ql+ZFpQCZniwkdY7Bwc=,iv:6tkfMQTCIwHaEnFHy1S2uwXGVKMAc26K9hUWu0YPpkk=,tag:QzQ4URKmSpyhfxXTpzfcsA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:Ojin+Q==,iv:jpFCfYm62XqwrErFGhmpLgo2nHDzo9nrer7WroLPqpI=,tag:cpp6jjH0VTGUiBaYDC7rQQ==,type:str]
    S3_REGION: ENC[AES256_GCM,data:td1eeIFpyAL6or8F,iv:lPr7JEw2ByaEQCZkQtWO9z14+0XQSuKYLW5/5IerUFM=,tag:L/uYZyimYQEc1Ay+M+5gJQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:zjvjidnPv123USKMyeEeuNog8f9NUM/qjmgsoi8h4pfMUNiOcAaAffyUuMl31SAzzjRHQec9LUSU35zB39kTpSYvhl0ypw==,iv:VBuUsmoRmsX97q1IedBIwi/xepNqbWoA97znvu+jLe0=,tag:ikb3VTjNjp42/8/wiSDToA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:X3pRhj0k/thkPr10l5BjJl0DHAzyQ4ztPDOEeuQSQvR2Jz6LPskeHw==,iv:K6WTcDpNll60wuEDK+h8gLmKZQ2xHARIRGCdrsQH7Ts=,tag:8DqImnw96dS5B0OYsLvMjw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yF789Kp60k19rU3mZgAjUW91g6qmzLJj+r5H2Q3gZoLPR0OC/JnFJsmqHP8=,iv:c0whHzobZAwdTwaqxiuAfHtjeIoYn8kcIR+nlQRkCqY=,tag:Bo7BALroXnmvFpzi/0hnTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVFhhWUQyQXNHeUFoMzlj
            WDJRKzhlSEZxK1ZaN0wySTczL2QyK1Z1elE0CmV2UU5sNStkRUpIa3NNS0I0N2Jy
            V3pNRkVjbzBYeVZEWWlsdlE2Vmg0VnMKLS0tIEZFaVEyZ1B1N1BWWDM1akJkVytF
            WWp0M2d2aGNUMUNnL1p4cDJCeFhoK3cKMPD9U7P7bhxI8ev5plcohiwk+zL0vS01
            T32OiiBFN+zKCiOYUT8raQbMTJ0qq5YPe3hX4j/2AyqxD7TZmLDCpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T21:29:21Z"
    mac: ENC[AES256_GCM,data:YZk96GFf5kvYEJkm1N4s1kGLsf7EzR8Mm2iPI+YG/RGE6M6i0oEYEakIAtze288TqBPSE4KMGHmrg+TFH8kmV2bKDHBafie7Woy3/8dXGvbhP7dHbYQuymHIfauaUZbc7r69oBpBjdF0dZNRK7Q3qYh9SwSKCKn1eIJFTF/MHo4=,iv:KXNtRkQJEy1tlandKP/GHBskOXPrjWhQAqD4Jkn+zZQ=,tag:X5qaicS/it4jxrfgOxgpuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
