apiVersion: v1
kind: Secret
metadata:
    name: pocketid-encryption-key
    namespace: oauth
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:6NZWzX/QiJAQXaJKxB5ruGN2GPt7GRidyAwNTn1cJUC6gY63K5h/aMMrAio=,iv:aH7u7BKNW7bMZE3ySTDyumjQxwNbX0wqA17JfIZhwPc=,tag:Uv10wm1x56lvVTGldUmHMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeWt2VSs0TmwvNlJwMGVp
            Vkd2Nm1KQWQzWVU5TGZ5K3k5RXZkWHJEN1RVCllKQWVhRmZvVXJ6ek9ObHJTL3hB
            MzJPWGZjai94NndPOUJHcXozQzF4RHcKLS0tIHVpT2lubVU4YlNKUlpKelpLV2NH
            Qnh5dHY3cFl2SWt0VVpCOGRMaTV6TDQKBoQ/WzTdTf2mtJVsa7v4MISEY+zQ83/k
            ndBme6tylcbJOvT6HDq5ueRwLef8yyV1yK2xWIq+H+WjJuGwTY/LKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:08:26Z"
    mac: ENC[AES256_GCM,data:1ki4NdG8YvJYrA0haIOGtJYUgnZQSFknfbJ4fl1NzYegw+Ab/CRJ9n0NpW7PoQKH1TFwB4T6+y8Qho51gfGE6X6UWkkImQNLKWYg0re+kJt8moPusNrcKQMSAlGmNBwummJ8QgR4kqTYvgSDkT81oXpjBj08L7+0v5rsmU3TlFY=,iv:RcMlNpzMDk2fP7tAmtfJGVMqNb9X+jnKVaM0a0D41rk=,tag:yqfohXHZ5ytdDUVsA1uRow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
