---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: gateway
spec:
  acme:
    email: "${ADMIN_EMAIL}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - dns01:
          cloudflare:
            email: "${ADMIN_EMAIL}"
            apiTokenSecretRef:
              name: cloudflare-api-key-secret
              key: api-key
