apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:PwEYHkUnuTqSkrUy3sTzC4ut/oR6zbbvYv1/EvDHgI0=,iv:z/h2WDwE2mk9BJYzJCGQxrKYay+Fxki9tIDEDbcikHY=,tag:1llJRYyHIdbAndq0cz+cmw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:x7xkd99ub+PV/I04NWtH01BBYZxN3S2YZVxFHpm/mD4=,iv:wlL0I0hPv1FqAnBqepxhMqUvzuPMDBYkbRX+O9sI4Kk=,tag:AX9Z+vmNSYZ93TMgViSyqQ==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:gE5h30wyiYN2JBTqU0poWGo6VKUWDOLiUtoQzTW4iyI=,iv:Sxo0pLnBIAIovtmHQjz6WnQhnWK7u7TW+qwPj9c/9HM=,tag:rgo0jeFytHFpuLlMA939Vw==,type:str]
    SEERR_API_KEY: ENC[AES256_GCM,data:rrlqxptqscYVll6g7+Cxw7rsN+V2jQcfxj7c,iv:QDIMLtDExBTsn5/u0Z+mfUUGvu88YIF+fFqjkKFxZFg=,tag:2COTlfHG4iFSkmK5kr5YLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNk9GMjF6cG5NOUtzYjNW
            cjF3K09UazFxYmRvODB2c0RmbWpCVmF6cHljCkFpd0JJR2QzZk1IRC9nMlI5L2Vu
            SGY3dFY0elhnT0drWGFjaUxzak0wWUUKLS0tIG1YcjRMakQ4VFgxRTVoakZDNFhZ
            endPYk1HbXIzUXNkRTNydXZRdE4vcFEKFKgbazXTP1gm9qV7eKR0NyQZgLfWqwxd
            sYIW4GukRtweeIbJhoabt/ZaFVnKU/b41ftQc5nKSd55infTLyabSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T21:10:54Z"
    mac: ENC[AES256_GCM,data:/2Ej9ITuuufCkdI9iOrXbgrvpwAPPoEjwPgg+sUcE7XqLcQ81/qSF9rkNj+Yfo60j1QxxAqM73C15KimHQuAAIm9jXxJufjKiFfXZBubuEJtxYw9NibCJNElo7m/Y21vFC55rP1JY23CGtCaArzDCrxYNTndrnoDjQS8zDE77vU=,iv:6aJ8pJ/8aYr/lWRxOr9xfE1wkJUXbZ0A8F8svlxmTS4=,tag:psW+hT58u3PyQgB90sz4VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
