apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:4OEfm0cZNbupc4Dabgc6IQovZRp6KPdQhpijKR2Nc54=,iv:0pPu2QVtbaV8tCfz3yPSfVxJK2WNiuZoND1NjVbfW2o=,tag:OrIkuWanrpqDph86IMQlrQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:OG8Pa2R4m+79lnFwPItzn/kW7fEkCi3W3EaVxWX+6Xc=,iv:RABRYWaSpCQEF0Ifn44a7QDj6QeOkP1AWLZkcmAsRqA=,tag:OJLo5o4zBZ+6BXDWy8+fmw==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:BMBVWg3VMY1K8wBlPjhsFeUxRfFBY+ZB9H87Y71BmPw=,iv:6xe5o8QT5APUPU0K/EdZoBNHe1ENN800IBJQeW0eJZg=,tag:60Oceoi6X/h82vkLNTD1pA==,type:str]
    SEERR_API_KEY: ENC[AES256_GCM,data:/+TTb2fdMfPUbM0vkJHUHBfW/TBH7f/WDKP7Sxb0/tveKHPV8VlNRe0BENPvl88NiJf/Kb0ntrxyTa1D8Dk3V6d3OPs=,iv:5r8sErgALeuEmlhwu58utICXoYNJFo6l0vyJv08f/ug=,tag:4CeIafFbUpsrcSQxYlDoQw==,type:str]
    TAUTULLI_API_KEY: ENC[AES256_GCM,data:VsG1+ncH37uZJkFfKbiRcCZDUoECsoptOGwz4nzEnr0=,iv:CoHA3+0kMwpktyA+i0AJqUxS9FL8vj+Dg5o32971W3A=,tag:CmjLxTBqKOl5Iv71a68gtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUU9ORnhES09zWW15MVZP
            dHloeDY2WmhUakV5ZHZycjRsTWt4K1FDV1E4ClBFTmhoL2NoZC9SbnV5Y1RtOVpH
            anJHK05DeDl1MzRCRXpIRktQTGtFUUEKLS0tIGljYjk1RnlPbi80dnZXeDBrc3VG
            SnNNbzh3bzFDZjhyR2FXaWJFanFPaDgKiRPVzwAYLLTxREwBy5+eL9QE6Nh38fL5
            +9CsH1d9y/wixeF1h7WmUdOAxhd61eIc6vdDnKRAkDPerDtOdWTVaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T01:32:13Z"
    mac: ENC[AES256_GCM,data:IBKKgj635s1Pp4u07fD2243J7xNDNOyiEIHGeCCcqlyAaiB3BrnnGorQOCCuenOceD//+q/j/VBk2Xqe+J8c3sT/DVQozfO4ysN8BCmE3F8y9meEjL82RngVf3+limTMqhv1P4UDX5UtDfrjMZtqRXvBtjHrb3DurRmUGTkhulc=,iv:VFP/BOmcgNZNDRup/nqwEi/AnKk7DQEoInYwhQsminU=,tag:KMvkv4Y0lGdXS983MIFHVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
