kind: Secret
apiVersion: v1
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:91lAkJjUSKzfjynvvFzBCvqojNQ3K3MCfAwxl1Loo0E=,iv:B7+yTD0q5FnozIKGVL5uFcfpMwnlala9OGDrmBriab0=,tag:YOegvux2X8f1gELGXmn4AA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:UJwCwVBBGI6IL2+KHjVKvrG66MZFJvNPZyvwFxWa3xw=,iv:6fJRjC7Ka6Pp1saV2H9X9lWn80LnYOhmZOwBJg6G3S0=,tag:IJVueeHJo26VGjbGOrbc7Q==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:LHiZp1yz/arryoSYezcAssW3fm6zn5I4/07wzsW7B3I=,iv:B+uijubof9u0PfejKTkUTmuZDOtsDU5XHc51WtiNd9I=,tag:ZVi/2RxO77stAMvobnEFOQ==,type:str]
    SEERR_API_KEY: ENC[AES256_GCM,data:cdGN2MBE4BJygLW6H+JQW8VbY8UqeA8THloU,iv:sqQyGTntVbTPaxksHzZGtvoHjEYt8tfRLA3mlVj630s=,tag:y7u/iuuflSvEs+PMWNnnZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcWNUOFRkOWNQaFpyd0hT
            d1lDdGNOZ0RWSW4vMTNxY29vRnFkU3paT1JZCms4ZFRmT1E0UitpUjYvYWZlMHJX
            VmVMMzFMam5KR1JOaU1IMEtQNFBmakEKLS0tIFVTQXMrakxqV0xRd210Tmdqb0VS
            cjZiRzgwNXFTN3VDTEt3NVR3VzdYRTAKCCLZoEFG72B4r3qll9L98AUf2E8gWtHN
            xw1RMOTb4zfiYhTkoGA6waU7f8Txei1AHFvnX4Tse81OSXKjgP0xRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T05:03:36Z"
    mac: ENC[AES256_GCM,data:J59KRbUJUIkHb7sx+tOglBYexgB7ZP0aiuhC/C2D4Sgeicejs88037pYFNR1FF+41VxcOqJovxqlXgqI1Dj3K52dqTwWkr9cs7lLFkdxkP0EGlfhS/ZvnOIvbBy9DuiHI2BctDVy1p+G6SUNmIlwzBRjHa4mEESvEfARwcZ3qSY=,iv:j3XcGAi8BskaJOkdBkZDZ5oP/gkSiLg5KWOyKnpUYjI=,tag:qWXZ8byRQsq4XAFo0GiIsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
