---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_PATH}/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: media-data-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-media-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_PATH}/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: arr-stack-media-pv
  resources:
    requests:
      storage: 10Gi