---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-configmap
  namespace: renovate
data:
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: "Renovate[bot] <${ADMIN_EMAIL}>"
  RENOVATE_PLATFORM: "github"
  RENOVATE_BASE_BRANCHES: "master"
  RENOVATE_GIT_COMMIT_SIGNING: "true"
