---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:42.57.1
              args:
                - gerulrich/quantumlab
              envFrom:
                - secretRef:
                    name: renovate-secrets
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never
