apiVersion: v1
kind: Secret
metadata:
    name: pocketid-secret
    namespace: pocketid
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:WKMWUA8niXUt3x9MyJcedF0cTuU+wskXR0xvkikerTFujywvD3YBJrjgz1k=,iv:K3creCREUdWjGdUOwvaaP3LbMowV0sP2/HEZMF3LMc4=,tag:NbcGbfSBpLOq3UzN3IO4uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOUN4NWJqWHhLdDVjZm01
            MzVpYXZwZVJ4Wm05SzRaYzFYZGkzRW4xVkg4ClFvL20rQWQ5Q2ZyT0VRWUIzYzVp
            WVVBOTJ5V3Jlc2FwRWRYYjlpOEVZdVkKLS0tIDZVeG94czVHTExpMEsyUEV5dkRZ
            bjFkSkp6NmR0OVdmd2dLNCs0eCtrcFkK9h+qDzqMQbaEMcUHzxyFpLEq344I6Jbl
            Ca85VmYyJF66ThCYSRg797AfKTzwKuPNleJke1IKeOxdkipmus1IoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T02:24:40Z"
    mac: ENC[AES256_GCM,data:jr48Nbp/2cKqqrA0fTJVjx7RxhWt0EDeW9rbfPlM2KzGtNx0xddmQr94qsu1NfOWo6rS2/r570rp1+QH0ccRaIVm5W7i4LECKptM5lBfqy3ihmvbF1F8od+KhPJevF6HTOjqD9kaqIcWXLbR9EU/3fH0Sra33byX1JKk8sM0QoQ=,iv:qy+KD27fkzWW838exgoefGL2y96+qNzR2zqh01ePeEY=,tag:8CHHaND05mjCxh5Ce0LYtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
