---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets-oci-bucket.yaml
  - secrets-pocketid.yaml
  - object-storage.yaml
  - cluster-production.yaml
  - scheduled-backup.yaml
