apiVersion: v1
kind: Secret
metadata:
    name: oci-bucket-secrets
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:RQNuA0Nsg7HxtHVRjVhev3ejuY92Nthu7l0XaDWF3IoNDu+Vm9QJzQ==,iv:ixlw4AuBdeXKOIisuPL6Cy3fd6JtXfim3sUU2+rhd0g=,tag:ieef8ygvhE/kh4wZH8GK/A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:3Ro90DcNbV0Zwlv1cspqE7/eXHg/Cj86RXZp7CWDEZhQzq1flQx9QxzVQi4=,iv:eKwtzy0nnJNhrIk7eUyExuijqciq/R/p2itHv8qTfUg=,tag:cHpGBORn0so27yf+V49GjA==,type:str]
    REGION: ENC[AES256_GCM,data:zLEjdes7O9xCuWi2,iv:SnnsjsnHwjb5HYkqSSDMgbsc+Gl5dO3Y2YJuS+WAM8g=,tag:/9r2EyEEq5uOpPlV2VRj7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRTBNblFZUUFKQThUQWZw
            UTViOURuVGZaRG56bi9CdHpNaU1qeXY5eUFnClV0cDZDaUZYdVRrWmpWRUp6b2ht
            Nk83RnFJNWttRlN2MG1TazdFN2tQOE0KLS0tIFY3dXpkZW10dXh3aVVja0dPWWJn
            eEVsS2xSMmsrZEtXNC9QVDVIcSt2amsKb2uV7OOuLi2cjJZWdGoVbR4zeu1v90oj
            qcRSlAJ9Tgh1NkW1HxSkJPyTVgpIY8K95zPN2tfGJgXHHTJ5b6x5Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T03:04:01Z"
    mac: ENC[AES256_GCM,data:bbmx9rrep+XPjoMD/xOmf9xFxQLeef6wrXlQv4WF9DUYWvHJVYunY5nyyW2DEbXiN9htQ/I/t8jaA9GMbWVhaZb9Mx4PNKgvw5XsnkDTI5XQHIHgpS9dPx42ZVUXOg46VFc86BS3+ildRZVWCF55ZWbN9yltZ0qTSF/UwNu9L64=,iv:+lYvaMSloxbiB89xj2cZmlD4YOKkDrm3NIi8rhenbZ0=,tag:QyW6e4gCnjY6fj6NiV00PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
