apiVersion: v1
kind: Secret
metadata:
    name: pocketid-credentials
    namespace: database
    annotations:
        kubed.appscode.com/sync: "oauth"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:un6f7Py2zbxxPr6r,iv:gjKo8s+t8vuXPkKzFHOhhsKQrXNeShS1VoO0l/gY/ks=,tag:L27HdnZEhXuhSa/YPnV1Wg==,type:str]
    password: ENC[AES256_GCM,data:tkW/l5aVNa2JoIRlfcIIvfb1YwTmLLSrmft/Fry2lYFzmmjYkkHD/3qJo1zpM7rNAfB95hcy0vkU53NDj7onCQ==,iv:EOW3TPqB1j+XmoLWTbuV0TBy/28PEkIOdpvhm3TYiVo=,tag:bBV7asEn0m9vlD8bmrR7jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON3RsYjkwTmtzbEFmZmJp
            b2tuaUhQTEY0RGt6b3JGRGlaSTJhSU52S3pVCndOK1dGN0dyR0s4RVU4b3RVd1FR
            a1piQThqenE3dVVGZGc3d0lRN2lyVEEKLS0tIGhpM2FueVVFNWNSMkZINlYvQ0di
            eUdsYUdseFVOK2FBUTB5ODhRN2xMR1EK2+A5YuFwzWDzG7DySy42nbLgLVE7In6l
            4jJxZJyII4SXYLXVkGBgeUxFmTpysZBZzlpP2ayYDhBAjpDH7g7MuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T03:39:49Z"
    mac: ENC[AES256_GCM,data:867jNHDIQmyYR7w70ffmjxzxxMkyqnJ3H/oo4Z7Lule6yczC5WLKbp6Hq5gHfXlKDBgzCG62ycCJsjiqFJ/wkSD0RGeO6qrtYUNWVZaPgX31xw99wUelC1uHx58zAc4WjRkptpyBy0PIp/kccV2pHSpCsdX33qB9Tkjs+zIsS84=,iv:hLzvCDH5+WhRFZZqyXG3fAx+O19kcC4wyylnuwP+Oac=,tag:Y09teAO8ziCbn7d3vZRc/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
