apiVersion: v1
kind: Secret
metadata:
    name: pocketid-credentials
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9jtARHDuAeJFjVlO,iv:F9+pu9f0mXSee0ofg5NjP6gmb22DElenHJMdgEVtWTU=,tag:cu3HBw3NoWGTj5tLXvVSTg==,type:str]
    password: ENC[AES256_GCM,data:E2Klhc1eIok7uHfmUr+0HneOcrD8HwyAmH9LPz2Pn75HjT2Y8Av9wVdL6WaF6e3aLaRbZ3wXn+HQQ2A/7xqg1w==,iv:OsH3d8mlSU4MMt9HlVQ72dAKex/K8Pmcmmi8LDXBvcM=,tag:mB7bTH7HIYn3HavevXHcxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU2lGQ3JORTdNRlJKSFBU
            Sk1ZOGFkeEwvMEYvYmFiUE96V0lLZFoyT2trCnFCam1PdzVUVDZ2UTEzZnluQ0hS
            NjV4aUZSZXF3QitSc1pGTjZOb1JEVDgKLS0tIFpjK0FZK0RqbWhldE5wVTBqV3Yz
            NXg4SWNIRE9UeWFpNkJ5QWxiMEZoajgKuBfNimL3Wpe4ldlTSXsUNFiIoUThjVVM
            VekJomkPcZMs2mT67Lnd86kpGvzawzWDfi8aX7W0jU/LUh2ZMm1L1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T03:09:02Z"
    mac: ENC[AES256_GCM,data:I8ZHoVUY8Z4gqCxegZE8Yhoo9o+ErNWKr/wB3rLO2dezDegYtx7NIYOt/Kq+zDm8ZInVVBp2/tsAb9Y5dF3TcxhXOV9UqwPGmuo3jUPvXObgTIS531RjQfcp4OLJnkAYif52nU87fs+IQleaSc7d1PVmok3zk40pJNed4LNPT7U=,iv:rRTCJTipBe+bR5pa0D5pkNnsW07tqf7bFpznO6Ej+WQ=,tag:vRYpmHjzhDusU+E7UYrgtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
