apiVersion: v1
kind: Secret
metadata:
    name: pocketid-credentials
    namespace: database
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: oauth
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CPYfogG4RLmtogVu,iv:mpQZ9LnWXlROpwORod4kxD6Ma4VYeieiDaMrSblQ+eo=,tag:fYbrif8KQSZqILDCkLFnWA==,type:str]
    password: ENC[AES256_GCM,data:dRYYZid5cb0yDfeySqV7SVC38niY5+DjeAazeRAdSiojcD3wkiTE67fKAiic9tdC6iRBVT+RxnZB+v+Oxwoc9A==,iv:ILP+jb/SAmBXsEX1bPm8Qz2bbBvsSRnlU4BrIr07dv8=,tag:jORux215YFW0a/x8/DHmWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZXpjYm9qSGpCYXllZ1FD
            b1RVQUl2a2NpbXFwZ29Eb1JCcUt0elZxQ0RZCjQ3ZURkSEZjemM4V081ZGlVUUdw
            L2FVK042YkRPKzlaaGFsYXJRZGNtSGcKLS0tIHlPZmFhOW5GbStxYUxpTHN1TXhM
            NmVqbnp1WlhLMXZWbUczVU9aMVFXN3cKAsWR9rMSYfWhy/8FLdsolDy7oB6m/Hyu
            EhZ5DbXHLCHCnznrTB3opDvXblKayElLgTdGth24wnJE7APU5tiLsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T14:59:05Z"
    mac: ENC[AES256_GCM,data:jgD2CzzPgUz83ZFR1hJuZMg1F/y2i7y9iDrHepDHD3TO+5j82/vE3T0jEifoo4dOY3YuMNXmv0gfQk1t3K7aQXJIKVMi4NtdZLYJuko2XB82Z+n8hrPmn5NjfDXaercA+NH2GLUqrnJfgKtcTmUU2Y+SrKTns7iE81ECfDnpoqA=,iv:Y4rkZGqRQNaGO10VZ75bbrZ97fDqCHjB1kGz4MGdfks=,tag:VyrIn1Qsr1HrjADKZTf49g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
