apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:CXIZgHNqKQPi6tPGswtBVFk=,iv:qXNSPiMpymfdkQk01LVZnKHFchXE48sjfBVgOn2BVbE=,tag:O+OFgFA7b8XBd5v9soHQsA==,type:str]
    client_secret: ENC[AES256_GCM,data:+0Iz3ViBGFpl61tCNmCczwP3ZoKCsOUztGmoD8iaL1kMo/IXnN+3JukmHOXmgv1wA9G7JdetoruNrDoTxAE3qA==,iv:VdPJEompsowD4k6S48uLuq+zsHOVeg6LnQfy0V0vPaw=,tag:wqrzDdEohKt4gncmEDVMoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUEdXYkp5ZDROWnlyNXdr
            TXdhdENVaGtlZ3psbkh5ZHd3aTl2YkxSRWpRCllPbnZvS1NJek4wS0NNS3VFRjkw
            YnpNSTVOUHVXZHlaMEpzUFlPdEJZY0UKLS0tIHFUV0VGb1BaOUx2WHFpRE5EZHcx
            Z1pVU3ZzelpTZGJ5a211cEdSdkVrOXcKTW6Nr0Bk8+tFZZKumRO9q6lp6VcIUNfg
            ZfWjpmK7EjDyMu3rQvkkyBl36ugAld1V19IydVxNWBsHoyckzSWbzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T04:03:03Z"
    mac: ENC[AES256_GCM,data:u+xxITj25Efnz/SK9HIBg+f4umUupIuaLUhsIOy7q+WJZmZ1j4LQm2L0nNp7OrzTPj7lt/VlTyg4tCbDmtqHUZV1zvHjAdKs874XtBXyCJn8AHH8RtyrYEqOOKAtJ/vKXt31NUZgysg7LQnEhOlKb4MbDN7TYQ83itTQzydg5iY=,iv:y9egxUNiaSXmMMa1f2FeQujpkxLfOPCcSSuzq8P+9z8=,tag:Ar0Bts+jlwWEjVsvLR5M4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
