apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qbjlJK+EdpJQQxwBxBN13AGI0KF9csggnMloczqqwsZptlJ2TI7DKQ==,iv:8k21wAdh5+i0BAQMJsBdxrcOQmaFO8L739UrQDb0EDk=,tag:4ff6Jo7TPaSdBPTP40COQw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ysc63TpxLaeNJ3QEveGCdJ3/4Ov4Pjmw4AlHpG45uGTRLl3rcajddJv74FE=,iv:KWlbjkokf5I3MrhT2/0ulSBVAME/TbA1SUgGU6b9UvA=,tag:ToPnZpV+dMnvK/yGeCr+zg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:MbJdjLEZi+qYTXldC1sqDs5xW0kRMk6x2yEilO+1PCNU0qoAXt6pZ2twNlyyA2dx97AEfEZTQbK2npnupifz0rMDpdu9Ig==,iv:5k4YOJw84XWTZAb4Lk5T9zuakrxoV4E9kXT+jE8KVKE=,tag:XqBjuXc8531cCQPM0nxedg==,type:str]
    AWS_CERT: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYmlpc29Vckx6djRuL3Z1
            YjJHWm0rYVlOejFucUttdmxZbDR3R1lQdkN3CmJrdk82cnZnTGRySGdNaHZ1WEVv
            NGEwa3JTUnA5TTRaTGdvWEc5WlpOSGsKLS0tIDFKbTRSeWkyTGxrTU5Od04zdzNW
            NllWUktBZVAyNmliWFYxZnI4b2F0OEUKwxPjccn3j6zb+Brboyn7HudI6CVphCI5
            OqS7BLBnctxiR92eYVDjhWlia1hSELjaKAw5y8w28/g1/woPkZeqsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T20:59:21Z"
    mac: ENC[AES256_GCM,data:d9F/dgpJRsXSAWc8JV7g2wcIDGI44AyEEFsMWQaqBDBd6Kuj6g1SJjRHLJFDDVFJbLtZrUueoMIb+yebx/N763SNxxdugHFoD8iPFQAxbaH61qzyPw4wWwgj7PLm8jJDABBXFf1WKo58RdQ2GhTfFfeCVM8AyDVtA448knVTX6I=,iv:ahS+6QFUU+SwSd7xOZbzoQFrdqVCKQR2cHwZPjIUhQE=,tag:4vr5fb95eUtKucYE/ZFbxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
