apiVersion: v1
kind: Secret
metadata:
    name: oci-bucket-secret
    namespace: longhorn-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: oauth,database,oauth
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:V3WDYoI8+m/naZSaibrNGpvqC/BGQotxPmcA/RKTaUkhun0NPdgvbg==,iv:wBy8aZiw8tckCJeyiPxr8qUa11lsWAzbxiARbkZRGX0=,tag:tAz3g1uABUf3es8KtXAYgg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:POYXI4YQp0EdgMXzOYr2WZ4NHkcGQDb9L3six2yzB3Er5Ar/e1f6hitNB18=,iv:DnpmFa7Qw6oE+JKITNEeyOMeIt1Oe0Wf2l+G199NWCk=,tag:nbY1svfIPRt7XLRQQHHo7w==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:slUQZJgd5JE6LsalrMhhFe6XEUbkQ4xlKQHb00AwOQbxl1GqTFpK2bIpeF9xo7l4Es0B12yreFqHo86jPLBwGXK4ZOeB2A==,iv:ChEJZcAeFEjOIUg1Leuxc4B01JIO2nJx+UXfBcKYXwA=,tag:DzabhVdomHZcWXdLSJvCYw==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:ghJswRSzP95xDKXo,iv:j9HfjJr1maubnq+QglrFt05oHVaRSXrbGTlUIRDaV6k=,tag:JGFtxD1VtuVpKzqMcdpy3w==,type:str]
    AWS_CERT: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYVNUWTR0QWlvakJpZWdI
            MVZwZkVreGM5MUd4V0tqL1o1bEg2cXdmdDNzCk56U2wyOXNpZVB3NmtJVXEwekxT
            dFY5dHJHSGtlMm5nZDVIYVhWWHR2NTgKLS0tIGdtNTdIWGw5YVE1NVc1dXlWek0w
            TVdwcXJjZFgzUlplZ0ZmS3RRTDRLK28K1wVvLXFoQ/73HNSTuE97EbDwybQuvJjW
            KN8GA64A44qTk68NFnRYTBCV5h0hiv8Ma5eo8OfTHVbEbFVuzuu3aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T20:37:10Z"
    mac: ENC[AES256_GCM,data:vWszFaze/GVWdvYm0LF4S1ixQI8taiCau60ehl6ALtGbV69PdQgMWJIeytxpThAD/2GiGmCNfmo4gLfkGP677jnx0twbPEUHlDVNVSV7kLteTOpDbFNw0EohrBocK3OUSIVi2a8zJ31soFjT+cooZ5Zi4I8pRM6Y2epK/F6Qwvw=,iv:x+iDSnmNTzEfjkJzm6Cy8yJPVgRkfDGBdM5K7io898o=,tag:KfbLoMojep9svXnF8DMOFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
