apiVersion: v1
kind: Secret
metadata:
    name: oci-bucket-secret
    namespace: longhorn-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: oauth,database,oauth,kube-system
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Lu3e7RhNad4XzCvg0D/hXdJVVt2xRS9FLde8CmTV1MVb9wWS/hniAw==,iv:3uP0sVgClx15xES5KO7cr+kojR+w1jQGc0V0yJi3VEc=,tag:EHnvCrUJZTtGszKb6s7sWw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:j7egTuCxMT8XMY8TCxzuV7Ay6VrddGLItqJxiQHTBj9t2TQIUNy2KEXLqMQ=,iv:VJYMOf4piQ6p5B99ENd/c7GN+ATXn9rldUEYRKqsIKA=,tag:fHaq3KfEZJnhBDSlx2+kbg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:69gAL2WIQUNRCId1Z2mFZA4gVLUh6bGP5szaRRJut9a0eet88KyU9RShOQzsBJYZQcS3yXzihyZ5j4MPpHO/TW9OCjeK+w==,iv:2QM/dcJwy/XEFikuBgilKzTPcxXlP2Bd4ubC6tUby8A=,tag:2sd6y+60FfY8IQl6dV4vAw==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:jzhRwER7r7/RSp40,iv:52+n47MfnS9LgCjl5O84UWd5xNGt2/MCE0hyP8WI4pY=,tag:hfHIZCSNrniEH7vVdzFafg==,type:str]
    AWS_CERT: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNFRaVm1oei9TRDhpOXJa
            SzIyeGJaRXVOQk1RTU5acUtIeWVZNjc3ejA0CmlZd0QwRDNYcUg5d1hNMGQ3TTFn
            dGM3RU5nWE9WK3lSaXJDYWJjYnBEcVEKLS0tIFVMT2cvaXhQT2FkbWw4UEJNNnRp
            WTlzeFJmUXRyQkxPZXFvS3NmZU5DbDAKaGliTWNOqjxyJGQG8Om9tKZSrwu+PS7v
            cCbwYSb3dYofbTabL/XbMJC1THWdem2G6SibuyzoGdGmwVZsmyvVAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T04:20:48Z"
    mac: ENC[AES256_GCM,data:1sxpXGDpoUYFlar54x1dTehE2vBFeSAfb/ujhSOkEpzQ+b6h+YXnm5d7y1oYD3fhd9WBtf4QHmW2bSQGP4wRo2a4RpC9Xf4I2HYhipLeDzYqnOvGl4kldVO//lcC1QSp0JOkvmthdddTe9NQU0tJrOZX4JfhV1TvgUMqPC/FO2M=,iv:ZeuXXwHg1WBFNfTtPxMANujkUTVKOb7hnhbdOR8LLNY=,tag:HCrCxkSZiu51QCmdMgFmFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
