---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  pihole.lan.conf: |
    server {
      listen 80;
      server_name pihole.lan.${DOMAIN};
      location / {
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_pass http://192.168.0.10/;
      }
    }
