---
name: Check YAML syntax

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Needed for tj-actions/changed-files

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **/*.yaml
            **/*.yml

      - name: Set up Python and install yamllint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint with reviewdog
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
